name: Deploy
run-name: ${{ inputs.apply && '[apply]' || '[plan]' }} ${{ inputs.environment }}

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      apply:
        type: boolean

concurrency:
  group: one-at-a-time

jobs:
  deploy:
    runs-on: macos-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Commit
        id: commit
        run: echo "message=$(git log -1 --pretty=%B)" >> "$GITHUB_OUTPUT"

      - name: Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: Test
        id: test
        run: pytest

      - name: Configuration
        id: configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        with:
          token: ${{ secrets.TERRAFORM_API_TOKEN }}
          organization: ${{ vars.TERRAFORM_ORGANIZATION_NAME }}
          workspace: ${{ vars.TERRAFORM_WORKSPACE_NAME }}
          speculative: ${{ !inputs.apply }}
          directory: ./terraform

      - name: Plan
        id: plan
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        with:
          token: ${{secrets.TERRAFORM_API_TOKEN }}
          organization: ${{ vars.TERRAFORM_ORGANIZATION_NAME }}
          workspace: ${{ vars.TERRAFORM_WORKSPACE_NAME }}
          configuration_version: ${{ steps.configuration.outputs.configuration_version_id }}
          plan_only: ${{ !inputs.apply }}
          message: '[${{ github.ref_name }}] ${{ steps.commit.outputs.message }}'
      
      - name: Apply
        id: apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        if: fromJSON(steps.plan.outputs.payload).data.attributes.actions.IsConfirmable
        with:
          token: ${{secrets.TERRAFORM_API_TOKEN }}
          organization: ${{ vars.TERRAFORM_ORGANIZATION_NAME }}
          run: ${{ steps.plan.outputs.run_id }}

      